---
# Create Production LUNs and Volumes for Oracle DBs on AIX
# LUNs/Volumes: home, logs1, logs2, arch, dataSID, tempSID
- hosts: all
  name: Create LUNS set for Oracle on AIX
  collections:
    - netapp.ontap
  vars_files:
    - vars/netapp_appliances.yaml
    - vars/storage_vars.yaml

  tasks:
# LUN machine_home
    - set_fact:
        suffix: "_home"
        size: {{ size_home }}
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
    - include: tasks/create_aixoracle_lun.yaml
# LUN logs1
    - set_fact:
        suffix: "_logs1"
        size: 18
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
    -include: tasks/create_aixoracle_lun.yaml

# LUN data
    - set_fact:
        suffix: "_data{{ OSID }} "
        size: {{ size_datasid }}
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
    -include: tasks/create_aixoracle_lun.yaml

      
