---
# Create Production LUNs and Volumes for Oracle DBs on AIX
# LUNs/Volumes: home, logs1, logs2, arch, dataSID, tempSID
- hosts: localhost
  name: Create LUNS set for Oracle on AIX
  collections:
    - netapp.ontap
  vars_files:
    - vars/netapp_appliances_aggr_02.yaml
    - vars/storage_vars.yaml

  tasks:
# LUN machine_home
    - include_tasks: tasks/create_aixoracle_lun.yaml
      vars:
        suffix: home
        size: "{{ size_home }}"
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"
# LUN logs1
    - include_tasks: tasks/create_aixoracle_lun.yaml
      vars:
        suffix: logs1
        size: 50
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"
# LUN logs2
    - include_tasks: tasks/create_aixoracle_lun.yaml
      vars:
        suffix: logs2
        size: 50
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"
# LUN arch
    - include_tasks: tasks/create_aixoracle_lun.yaml
      vars:
        suffix: arch
        size: "{{ size_arch }}"
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"
# LUN data
    - include_tasks: tasks/create_aixoracle_lun.yaml
      vars:
        suffix: "data{{ OSID }}"
        size: "{{ size_datasid }}"
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"
# LUN temp
    - include_tasks: tasks/create_aixoracle_lun.yaml
      vars:
        suffix: "temp{{ OSID }}"
        size: "{{ size_tempsid }}"
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"

      
