---
# Create Production LUNs and Volumes for Oracle DBs on AIX
# LUNs/Volumes: home, logs1, logs2, arch, dataSID, tempSID
- hosts: localhost
  name: Create LUNS set for Oracle on AIX with snapmirror relationship
  collections:
    - netapp.ontap
  vars_files:
    - vars/netapp_appliances_aggr_02.yaml
    - vars/storage_vars.yaml

  tasks:
# LUN machine_home
    - include_tasks: tasks/create_aixoracle_lun_and_snapmirror.yaml
      vars:
        suffix: ol
        size: 1
        src_volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ src_volname }}"
        dest_volname: "dr{{ machine }}_{{ suffix }}"
        dest_rf_volname: "dr{{ machine }}_rf_{{ suffix }}"


      
