---
# Create Production LUNs and Volumes for Oracle DBs on AIX
# LUNs/Volumes: home, logs1, logs2, arch, dataSID, tempSID
- hosts: localhost
  name: Create LUNS set for Oracle on AIX
  collections:
    - netapp.ontap
  vars_files:
    - vars/netapp_appliances.yaml
    - vars/storage_vars.yaml

  tasks:
# LUN machine_home
    - include_tasks: tasks/Prod_maplun.yaml
      vars:
        suffix: home
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
        lunpath: "{{ '/' + volname + '/' + lunname }}"
# LUN logs1
    - include_tasks: tasks/Prod_maplun.yaml
      vars:
        suffix: logs1
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
        lunpath: "{{ '/' + volname + '/' + lunname }}"
# LUN logs2
    - include_tasks: tasks/Prod_maplun.yaml
      vars:
        suffix: logs2
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
        lunpath: "{{ '/' + volname + '/' + lunname }}"
# LUN arch
    - include_tasks: tasks/Prod_maplun.yaml
      vars:
        suffix: arch
        volname: "{{ machine }}_{{ suffix }}"
        lunname: "{{ volname }}"
        lunpath: "{{ '/' + volname + '/' + lunname }}"
# LUN data
    - include_tasks: tasks/Prod_maplun.yaml
      vars:
        suffix: "data{{ OSID }}"
        size: "{{ size_datasid }}"
        lunname: "{{ volname }}"
        lunpath: "{{ '/' + volname + '/' + lunname }}"
# LUN temp
    - include_tasks: tasks/Prod_maplun.yaml
      vars:
        suffix: "data{{ OSID }}"
        size: "{{ size_tempsid }}"
        lunname: "{{ volname }}"
        lunpath: "{{ '/' + volname + '/' + lunname }}"

      
