---
- name: Create dest refresh (_rf_)volume by cloning the mirrored volume
  na_ontap_volume_clone:
    state: present
    name: "{{ dest_rf_volname }}"
    parent_volume: "{{ dest_volname }}"
    junction_path: "/{{ dest_rf_volname }}"
    parent_snapshot: "{{ src_volname }}_tempbkp"
    vserver: "{{ dest_vserver }}"
    hostname: "{{ dest_hostname }}"
    username: "{{ dest_username }}"
    password: "{{ dest_password }}"
    https: true
    validate_certs: false
    split: yes
- name: Rename RF LUN (just cloned)
  na_ontap_lun:
    state: present
    vserver: "{{ dest_vserver }}"
    name: "{{ dest_rf_volname }}"
    from_name: "{{ lunname }}"
    flexvol_name: "{{ dest_rf_volname }}"
    hostname: "{{ dest_hostname }}"
    username: "{{ dest_username }}"
    password: "{{ dest_password }}"
    https: true
    validate_certs: false
- name: Delete temporary snapshot
  na_ontap_snapshot:
    state: absent
    snapshot: "{{ src_volname }}_tempbkp"
    volume: "{{ dest_volname }}"
    vserver: "{{ dest_vserver }}"
    username: "{{ dest_username }}"
    password: "{{ dest_password }}"
    hostname: "{{ dest_hostname }}"
    https: true
    validate_certs: false
