---
- name: Create source volume
  na_ontap_volume:
    state: present
    name: "{{ src_volname }}"
    aggregate_name: "{{ src_aggr }}"
    size: "{{ size }}" 
    size_unit: gb
    junction_path: "/{{ src_volname }}"
    space_guarantee: "none"
    type: RW
    volume_security_style: unix
    vserver: "{{ src_vserver }}"
    hostname: "{{ src_hostname }}"
    username: "{{ src_username }}"
    password: "{{ src_password }}"
    https: true
    validate_certs: false
- name: Create source LUN
  na_ontap_lun:
    state: present
    vserver: "{{ src_vserver }}"
    name: "{{ lunname }}"
    flexvol_name: "{{ src_volname }}"
    size: "{{ size }}"
    size_unit: gb
    ostype: "{{ ostype }}"
    space_reserve: False
    https: true
    validate_certs: false
    hostname: "{{ src_hostname }}"
    username: "{{ src_username }}"
    password: "{{ src_password }}"
- name: Create snapshot of source volume to be used as clone base for rf volumes at DR
  na_ontap_snapshot:
    state: present
    snapshot: "{{ src_volname }}_tempbkp"
    volume: "{{ src_volname }}"
    vserver: "{{ src_vserver }}"
    username: "{{ src_username }}"
    password: "{{ src_password }}"
    hostname: "{{ src_hostname }}"
    https: true
    validate_certs: false
- name: Create dest volume
  na_ontap_volume:
    state: present
    name: "{{ dest_volname }}"
    aggregate_name: "{{ dest_aggr }}"
    size: "{{ size }}" 
    size_unit: gb
    type: DP
    vserver: "{{ dest_vserver }}"
    hostname: "{{ dest_hostname }}"
    username: "{{ dest_username }}"
    password: "{{ dest_password }}"
    https: true
    validate_certs: false
- name: Create Snapmirror
  na_ontap_snapmirror:
    state: present
    connection_type: ontap_ontap
    source_endpoint:
      path: "{{ src_vserver + ':' + src_volname }}"
    destination_endpoint:
      path: "{{ dest_vserver + ':' + dest_volname }}"
    initialize: yes
    relationship_type: data_protection
    schedule: 5min
    relationship_state: active
    policy: DPDefault
    hostname: "{{ dest_hostname }}"
    username: "{{ dest_username }}"
    password: "{{ dest_password }}"
    https: true
    validate_certs: false

    
